version: '3.3'

services:
  devops-hello:
    image: elaynelemos/vue:node-12.19
    container_name: devops_hello_app
    working_dir: /home/devops_hello/
    volumes:
      - ./:/home/devops_hello/
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    entrypoint:
      - bash
